[package]
authors = [""]
name = "begin"
version = "0.1.0"
edition = "2024"

[dependencies]
ginc = { path = "../ginc" }
clap = { version = "4.5.41", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
